backend:
  name: git-gateway
  branch: main

site_url: https://pfrac.chrishodgson.co.uk

media_folder: public/static/uploads
public_folder: /uploads

collections:
  - name: 'posts' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Posts' # Used in the UI
    label_singular: 'Post' # Used in the UI, ie: "New Post"
    description: >
      Information about races, training, results and other clubs news to appear on the blog.
    folder: 'data/_posts'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    summary: '{{title}} -- {{year}}/{{month}}/{{day}}'
    create: true # Allow users to create new documents in this collection
    view_filters:
      - label: Drafts
        field: draft
        pattern: true
    view_groups:
      - label: Drafts
        field: draft
    fields: # The fields each document in this collection have
      - { label: 'Title', name: 'title', widget: 'string', required: true, tagname: 'h1' }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: false }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'date',
          required: true,
          date_format: 'YYYY-MM-DD',
        }
      - { label: 'Cover Image', name: 'image', widget: 'image', required: false, tagname: '' }
      - { label: 'Text', name: 'text', widget: 'text', hint: 'Plain text, not markdown' }
      - {
          label: 'Body',
          name: 'body',
          widget: 'markdown',
          required: true,
          hint: 'Main content goes here. You can insert tables using http://tablesgenerator.com/markdown_tables',
        }

  - name: 'pages' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Pages' # Used in the UI
    folder: 'data/_pages'
    create: true # Allow users to create new documents in this collection
    view_filters:
      - label: Drafts
        field: draft
        pattern: true
    view_groups:
      - label: Drafts
        field: draft
    fields: # The fields each document in this collection have
      - { label: 'Title', name: 'title', widget: 'string', required: true, tagname: 'h1' }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: false }
      - {
          label: 'Body',
          name: 'body',
          widget: 'markdown',
          required: true,
          hint: 'Main content goes here. You can insert tables using http://tablesgenerator.com/markdown_tables',
        }
