backend:
  name: git-gateway
  branch: main

site_url: https://pfrac.chrishodgson.co.uk

media_folder: "static/uploads"
#public_folder: "assets"

collections:
  - name: 'news' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'News' # Used in the UI
    label_singular: 'Article' # Used in the UI, ie: "New Post"
    description: Information about races, training, results and any other clubs news.
    folder: 'data/_articles'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    preview_path: news/{{slug}}
    summary: '{{title}} -- {{year}}/{{month}}/{{day}}'
    create: true # Determines whether users can create new documents in this collection
    view_filters:
      - label: Enabled
        field: enabled
        pattern: true
    view_groups:
      - label: Enabled
        field: enabled
    fields: # The fields each document in this collection have
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Enabled', name: 'enabled', widget: 'boolean', default: true }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'date',
          required: true,
          date_format: 'YYYY-MM-DD',
        }
      - { label: "Tags", name: "tags", widget: "list" }
      - {
          label: 'Summary',
          name: 'summary',
          widget: 'text',
          required: true,
          hint: 'Short summary to appear in news listing'
        }
      - {
          label: 'Main Content',
          name: 'body',
          widget: 'markdown',
          required: true,
          hint: 'Main content. Create your tables using http://tablesgenerator.com/markdown_tables'
        }
      # - label: "Files"
      #   name: "files"
      #   widget: "list"
      #   summary: '{{fields.file}}'
      #   field: { label: File, name: file, widget: file, required: true }

  - name: 'races' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Races' # Used in the UI
    folder: 'data/_pages/races'
    preview_path: races/{{slug}}
    create: false # Determines whether users can create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: 'Title', name: 'title', widget: 'string', required: true, tagname: 'h1' }
      - { label: 'Category', name: 'category', widget: 'select', options: ['Fell', 'Trail', 'Road'], default: 'Fell', required: true }
      - { label: 'Start date / time', name: 'start_date_time', widget: 'string', required: true }
      - { label: 'Distance', name: 'distance', widget: 'string', required: true }
      - { label: 'Strava Segment url (ie for iframe)', name: 'strava_url', widget: 'string', hint: 'ie https://www.strava.com/segments/30806210/embed' }
      - { label: 'Google maps url (ie for iframe)', name: 'google_maps_url', widget: 'string', hint: 'ie https://calendar.google.com/calendar/embed?src=Y2hyaXNob2' }
      - { label: 'Entry', name: 'entry', widget: 'text' }
      - { label: 'Registration', name: 'registration', widget: 'text' }
      - { label: 'Organiser', name: 'organiser', widget: 'text' }
      - {
          label: 'Main Content',
          name: 'body',
          widget: 'markdown',
          hint: 'Create your tables using http://tablesgenerator.com/markdown_tables'
        }

  - name: 'competitions' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Competitions' # Used in the UI
    folder: 'data/_pages/competitions'
    preview_path: competitions/{{slug}}
    create: false # Determines whether users can create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: 'Title', name: 'title', widget: 'string', required: true, tagname: 'h1' }
      - {
          label: 'Main content',
          name: 'body',
          widget: 'markdown',
          required: true,
          hint: 'Create your tables using http://tablesgenerator.com/markdown_tables'
        }

  - name: 'about' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'About' # Used in the UI
    folder: 'data/_pages/about'
    preview_path: about/{{slug}}
    create: false # Determines whether users can create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: 'Title', name: 'title', widget: 'string', required: true, tagname: 'h1' }
      - {
          label: 'Main Content',
          name: 'body',
          widget: 'markdown',
          required: true,
          hint: 'Main content. Create your tables using http://tablesgenerator.com/markdown_tables'
        }

  - name: 'pages' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Other Pages' # Used in the UI
    folder: 'data/_pages'
    preview_path: {{slug}}
    create: false # Determines whether users can create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: 'Title', name: 'title', widget: 'string', required: true, tagname: 'h1' }
      - {
          label: 'Main Content',
          name: 'body',
          widget: 'markdown',
          required: true,
          hint: 'Main content. Create your tables using http://tablesgenerator.com/markdown_tables'
        }

